name = "Sky130PDK"
uuid = "3a9dc963-4db1-4336-a55a-41e26ba2a676"
authors = ["JuliaHub, Inc. and other contributors"]
version = "0.4.0"

[workspace]
projects = ["docs", "test"]

[deps]
BSIM4 = "fa7570ea-a14f-11ec-018e-d96f3217f940"
CedarSim = "9075980a-f0c7-46d2-945a-cc5bead5ad4a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
