---
steps:
  - label: ":closed_lock_with_key: Launch signed pipelines"
    plugins:
      - staticfloat/cryptic#v2:
          signed_pipelines:
            - pipeline: .buildkite/documentation.yml
              signature_file: .buildkite/documentation.yml.signature
    command: "true"
    env:
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    agents:
      cryptic_capable: true
      os: "linux"
      arch: "x86_64"
